model:
  model_name: logreg

train:
  number_epoch: 100
  learning_rate: 0.01
  train_size: 0.8
  val_size: 0.2
  batch_size: 16

infer:
  batch_size: 16

mlflow:
  exp_name: base
  tracking_uri: http://127.0.0.1:5000
  artifact_root: .logs/ml-flow

onnx:
  save: True
  path_to_save: "nvidia-triton/model_repository/onnx-logreg/1"
